main: "eu.decentsoftware.holograms.plugin.DecentHologramsPlugin"
api-version: 1.19
softdepend:
  - "PlaceholderAPI"
  - "HeadDatabase"
  - "ProtocolLib"
name: "DecentHolograms"
description: ${description}
version: ${version}
author: d0by

folia-supported: true

commands:
  decentholograms:
    aliases: [dh, holograms, hologram, holo]
    usage: "/decentholograms <args>"
    description: "The main command of DecentHolograms plugin."

permissions:
  dh.admin:
    description: "Allows player to use DecentHolograms."
  dh.default:
    default: true
    description: "Allows player to see the version after using '/decentholograms'."